version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: backend_taller_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=dev-secret-key-not-for-production
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend_taller_dev
    depends_on:
      - db

volumes:
  postgres_data:
