# Generated by Django 5.2.6 on 2025-10-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión')], max_length=20)),
                ('modulo', models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Autenticacion', 'Autenticación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['usuario'], name='bitacora_usuario_a680ec_idx'), models.Index(fields=['fecha_accion'], name='bitacora_fecha_a_4bdc12_idx'), models.Index(fields=['modulo'], name='bitacora_modulo_298c06_idx')],
            },
        ),
    ]
