# Generated by Django 5.2 on 2025-10-12 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0002_bitacora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['ip_address'], name='bitacora_ip_addr_1d3c1b_idx'),
        ),
    ]
