# Generated by Django 5.2.6 on 2025-10-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0011_alter_item_area'),
        ('personal_admin', '0003_bitacora_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('Autenticacion', 'Autenticación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='operaciones_inventario.area'),
        ),
    ]
