# Generated by Django 5.2.6 on 2025-10-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0004_alter_bitacora_modulo_alter_empleado_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('OrdenTrabajo', 'Orden de Trabajo'), ('Autenticacion', 'Autenticación')], max_length=20),
        ),
    ]
