# Generated by Django 5.2 on 2025-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0006_alter_bitacora_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('CONSULTAR', 'Consultar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('OrdenTrabajo', 'Orden de Trabajo'), ('Presupuesto', 'Presupuesto'), ('Autenticacion', 'Autenticación'), ('ReconocimientoPlacas', 'Reconocimiento de Placas')], max_length=20),
        ),
    ]
