# Generated by Django 5.2.6 on 2025-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0007_alter_bitacora_accion_alter_bitacora_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('OrdenTrabajo', 'Orden de Trabajo'), ('Presupuesto', 'Presupuesto'), ('Autenticacion', 'Autenticación'), ('ReconocimientoPlacas', 'Reconocimiento de Placas'), ('Cita', 'Cita')], max_length=20),
        ),
    ]
