# Generated by Django 5.2.6 on 2025-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0009_tenant_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('OrdenTrabajo', 'Orden de Trabajo'), ('Presupuesto', 'Presupuesto'), ('Autenticacion', 'Autenticación'), ('ReconocimientoPlacas', 'Reconocimiento de Placas'), ('Cita', 'Cita'), ('Reporte', 'Reporte')], max_length=20),
        ),
    ]
