# Generated by Django 5.2.6 on 2025-11-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0010_alter_bitacora_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='personal_admin.tenant'),
            preserve_default=False,
        ),
    ]
