# Generated by Django 5.2.6 on 2025-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ci',
            field=models.CharField(max_length=30, verbose_name='CI'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('nombre', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('ci', 'tenant')},
        ),
    ]
