# Generated by Django 5.2.6 on 2025-11-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0012_alter_cargo_nombre_alter_empleado_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='codigo_invitacion',
            field=models.CharField(blank=True, help_text='Código único para invitar usuarios al taller', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='horarios',
            field=models.TextField(blank=True, help_text='Ej: Lunes a Viernes 8:00-18:00, Sábado 9:00-14:00', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller_propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
