# Generated by Django 5.2.6 on 2025-11-24 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0013_tenant_codigo_invitacion_tenant_email_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Vehiculo', 'Vehículo'), ('Item', 'Item'), ('OrdenTrabajo', 'Orden de Trabajo'), ('Presupuesto', 'Presupuesto'), ('Autenticacion', 'Autenticación'), ('ReconocimientoPlacas', 'Reconocimiento de Placas'), ('Cita', 'Cita'), ('Reporte', 'Reporte'), ('Asistencia', 'Asistencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_faltantes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('extra', 'Extra')], default='incompleto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal_admin.empleado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal_admin.tenant')),
            ],
            options={
                'db_table': 'asistencia',
                'ordering': ['-fecha', 'empleado'],
                'indexes': [models.Index(fields=['empleado'], name='asistencia_emplead_36731c_idx'), models.Index(fields=['fecha'], name='asistencia_fecha_b120c8_idx'), models.Index(fields=['estado'], name='asistencia_estado_f6ec86_idx')],
                'unique_together': {('empleado', 'fecha', 'tenant')},
            },
        ),
    ]
