# Generated by Django 5.2.6 on 2025-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0014_alter_bitacora_modulo_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fecha_fin_suscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='fecha_inicio_suscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuito (Prueba 14 días)'), ('BASIC', 'Plan Básico'), ('PRO', 'Plan Pro'), ('ENTERPRISE', 'Plan Empresarial')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suscripcion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
