# Generated by Django 5.2.6 on 2025-11-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0014_alter_bitacora_modulo_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('total_nomina', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total de la Nómina')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='personal_admin.tenant')),
            ],
            options={
                'db_table': 'nomina',
                'ordering': ['-fecha_inicio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Base')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Horas Extras')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Bruto')),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Descuentos')),
                ('sueldo_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sueldo Neto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nomina', to='personal_admin.empleado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nomina', to='personal_admin.tenant')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='personal_admin.nomina')),
            ],
            options={
                'db_table': 'detalle_nomina',
                'ordering': ['empleado__apellido', 'empleado__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['tenant', 'mes'], name='nomina_tenant__fc747f_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['fecha_inicio'], name='nomina_fecha_i_7f07db_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['estado'], name='nomina_estado_1e9c4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together={('tenant', 'mes', 'fecha_inicio', 'fecha_corte')},
        ),
        migrations.AddIndex(
            model_name='detallenomina',
            index=models.Index(fields=['nomina'], name='detalle_nom_nomina__8cc2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='detallenomina',
            index=models.Index(fields=['empleado'], name='detalle_nom_emplead_59b918_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallenomina',
            unique_together={('nomina', 'empleado')},
        ),
    ]
