# Generated by Django 5.2.6 on 2025-11-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0016_historialpagosuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='suscripcion_activa',
            field=models.BooleanField(default=True),
        ),
    ]
