# Generated by Django 5.2.6 on 2025-11-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0015_devicetoken'),
        ('personal_admin', '0015_nomina_detallenomina_and_more'),
        ('personal_admin', '0017_alter_tenant_suscripcion_activa'),
    ]

    operations = [
    ]
