# Generated by Django 5.2.6 on 2025-10-10 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fabricante', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Item de venta', 'Item de venta'), ('Item de taller', 'Item de taller'), ('Servicio', 'Servicio')], max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones_inventario.area')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=40, null=True, verbose_name='VIN')),
                ('numero_motor', models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de Motor')),
                ('numero_placa', models.CharField(max_length=20, unique=True, verbose_name='Número de Placa')),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('version', models.CharField(blank=True, max_length=40, null=True, verbose_name='Versión')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('año', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('cilindrada', models.IntegerField(blank=True, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de Combustible')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes_servicios.cliente')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='operaciones_inventario.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='operaciones_inventario.modelo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
                'unique_together': {('numero_placa',)},
            },
        ),
    ]
