# Generated by Django 5.2.6 on 2025-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='area',
            name='operaciones_nombre_251b33_idx',
        ),
        migrations.RemoveIndex(
            model_name='area',
            name='operaciones_activo_49c659_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='operaciones_area_id_a1095a_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='operaciones_nombre_914ba1_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='operaciones_activo_066bac_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='operaciones_categor_9107ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='operaciones_nombre_3b4473_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='operaciones_activo_21ea15_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='operaciones_precio_bf3869_idx',
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del servicio', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
