# Generated by Django 5.2.6 on 2025-10-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0004_alter_item_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
