# Generated by Django 5.2.6 on 2025-10-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0005_alter_item_fabricante_alter_item_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['marca__nombre', 'nombre'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='operaciones_inventario.marca'),
        ),
    ]
