# Generated by Django 5.2.6 on 2025-10-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0005_alter_item_fabricante_alter_item_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
