# Generated by Django 5.2.6 on 2025-10-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_servicios', '0001_initial'),
        ('operaciones_inventario', '0005_alter_item_fabricante_alter_item_precio_and_more'),
        ('personal_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_inspeccion', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='personal_admin.empleado')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'db_table': 'inspeccion',
            },
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aceite_motor', models.CharField(blank=True, choices=[('bueno', 'Buen estado'), ('malo', 'Mal estado')], max_length=20, null=True)),
                ('Filtros_VH', models.CharField(blank=True, choices=[('bueno', 'Buen estado'), ('malo', 'Mal estado')], max_length=20, null=True)),
                ('nivel_refrigerante', models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, null=True)),
                ('pastillas_freno', models.CharField(blank=True, choices=[('bueno', 'Buen estado'), ('malo', 'Mal estado')], max_length=20, null=True)),
                ('Estado_neumaticos', models.CharField(blank=True, choices=[('bueno', 'Buen estado'), ('malo', 'Mal estado')], max_length=20, null=True)),
                ('estado_bateria', models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, null=True)),
                ('estado_luces', models.CharField(blank=True, choices=[('bueno', 'Buen estado'), ('malo', 'Mal estado')], max_length=20, null=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones_inventario.inspeccion')),
            ],
            options={
                'verbose_name': 'Detalle de Inspección',
                'verbose_name_plural': 'Detalles de Inspección',
                'db_table': 'detalle_inspeccion',
            },
        ),
        migrations.CreateModel(
            name='InventarioVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_vehiculo', to='operaciones_inventario.item')),
            ],
            options={
                'verbose_name': 'Inventario de Vehiculo',
                'verbose_name_plural': 'Inventarios de Vehiculos',
                'db_table': 'inventario_vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventarioVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('extintor', models.BooleanField(default=False)),
                ('botiquin', models.BooleanField(default=False)),
                ('antena', models.BooleanField(default=False)),
                ('llanta_repuesto', models.BooleanField(default=False)),
                ('documentos', models.BooleanField(default=False)),
                ('encendedor', models.BooleanField(default=False)),
                ('pisos', models.BooleanField(default=False)),
                ('luces', models.BooleanField(default=False)),
                ('llaves', models.BooleanField(default=False)),
                ('gata', models.BooleanField(default=False)),
                ('herramientas', models.BooleanField(default=False)),
                ('tapas_ruedas', models.BooleanField(default=False)),
                ('triangulos', models.BooleanField(default=False)),
                ('inventario_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones_inventario.inventariovehiculo')),
            ],
            options={
                'verbose_name': 'Item de Inventario de Vehiculo',
                'verbose_name_plural': 'Items de Inventarios de Vehiculos',
                'db_table': 'item_inventario_vehiculo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fallo_requerimiento', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('kilometraje', models.IntegerField()),
                ('nivel_combustible', models.PositiveSmallIntegerField(choices=[(0, 'E (Vacío)'), (1, '1/4'), (2, '1/2'), (3, '3/4'), (4, 'F (Lleno)')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clientes_servicios.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='operaciones_inventario.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'db_table': 'orden_trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaOrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nota', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='operaciones_inventario.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Nota de Orden de Trabajo',
                'verbose_name_plural': 'Notas de Ordenes de Trabajo',
                'db_table': 'nota_orden_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_vehiculo', to='operaciones_inventario.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='operaciones_inventario.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='ImagenOrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='operaciones_inventario.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Imagen de Orden de Trabajo',
                'verbose_name_plural': 'Imagenes de Ordenes de Trabajo',
                'db_table': 'imagenes_orden_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='operaciones_inventario.item')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones_inventario.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Trabajo',
                'verbose_name_plural': 'Detalles de Ordenes de Trabajo',
                'db_table': 'detalle_orden_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_tecnicos', to='personal_admin.empleado')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tecnicos', to='operaciones_inventario.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Asignación de Técnico',
                'verbose_name_plural': 'Asignaciones de Técnicos',
                'db_table': 'asignacion_tecnico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prueba', models.DateTimeField(auto_now_add=True)),
                ('tipo_prueba', models.CharField(choices=[('inicial', 'Inicial'), ('intermedio', 'Intermedio'), ('final', 'Final')], max_length=20)),
                ('kilometraje_inicio', models.IntegerField(blank=True, null=True)),
                ('kilometraje_final', models.IntegerField(blank=True, null=True)),
                ('ruta', models.TextField()),
                ('frenos', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20)),
                ('motor', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20)),
                ('suspension', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20)),
                ('direccion', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20)),
                ('observaciones', models.TextField()),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ruta', to='operaciones_inventario.ordentrabajo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_ruta', to='personal_admin.empleado')),
            ],
            options={
                'verbose_name': 'Prueba de Ruta',
                'verbose_name_plural': 'Pruebas de Ruta',
                'db_table': 'pruebas_ruta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TareaOrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='operaciones_inventario.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Tarea de Orden de Trabajo',
                'verbose_name_plural': 'Tareas de Ordenes de Trabajo',
                'db_table': 'tareas_orden_trabajo',
                'ordering': ['id'],
            },
        ),
    ]
