# Generated by Django 5.2.6 on 2025-10-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0006_presupuesto_detallepresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='operaciones_inventario.vehiculo'),
        ),
    ]
