# Generated by Django 5.2.6 on 2025-10-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0006_inspeccion_detalleinspeccion_inventariovehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='item_personalizado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
