# Generated by Django 5.2.6 on 2025-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0006_alter_modelo_options_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CAMIONETA', 'Camioneta'), ('DEPORTIVO', 'Deportivo'), ('FURGON', 'Furgón'), ('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('CITYCAR', 'CityCar')], max_length=20, null=True, verbose_name='Tipo de Vehículo'),
        ),
    ]
