# Generated by Django 5.2.6 on 2025-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0007_detalleordentrabajo_item_personalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kilometraje',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='nivel_combustible',
            field=models.PositiveSmallIntegerField(choices=[(0, 'E (Vacío)'), (1, '1/4'), (2, '1/2'), (3, '3/4'), (4, 'F (Lleno)')], default=0),
        ),
    ]
