# Generated by Django 5.2.6 on 2025-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0007_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_placa',
            field=models.CharField(error_messages={'blank': 'El número de placa es obligatorio.', 'null': 'El número de placa es obligatorio.', 'unique': 'Ya existe un vehículo con este número de placa.'}, max_length=20, unique=True, verbose_name='Número de Placa'),
        ),
    ]
