# Generated by Django 5.2.6 on 2025-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0007_alter_area_nombre_alter_item_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
