# Generated by Django 5.2.6 on 2025-10-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0008_alter_ordentrabajo_kilometraje_and_more'),
        ('operaciones_inventario', '0008_alter_vehiculo_numero_placa'),
    ]

    operations = [
    ]
