# Generated by Django 5.2.6 on 2025-10-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0008_item_costo'),
        ('operaciones_inventario', '0009_merge_20251012_1244'),
    ]

    operations = [
    ]
