# Generated by Django 5.2.6 on 2025-10-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0010_merge_0008_item_costo_0009_merge_20251012_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='operaciones_inventario.area'),
        ),
    ]
