# Generated by Django 5.2.6 on 2025-10-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0007_presupuesto_vehiculo'),
        ('operaciones_inventario', '0011_alter_item_area'),
    ]

    operations = [
    ]
