# Generated by Django 5.2.6 on 2025-10-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0012_merge_0007_presupuesto_vehiculo_0011_alter_item_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='con_impuestos',
            field=models.BooleanField(default=False),
        ),
    ]
