# Generated by Django 5.2.6 on 2025-10-17 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0013_inspeccion_detalleinspeccion_inventariovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='detalleordentrabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
