# Generated by Django 5.2.6 on 2025-10-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0013_presupuesto_con_impuestos'),
        ('operaciones_inventario', '0014_detalleordentrabajo_descuento_porcentaje_and_more'),
    ]

    operations = [
    ]
