# Generated by Django 5.2.6 on 2025-10-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0016_detallepresupuesto_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepresupuesto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='descuento',
        ),
    ]
