# Generated by Django 5.2.6 on 2025-10-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_servicios', '0001_initial'),
        ('operaciones_inventario', '0017_remove_detallepresupuesto_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='clientes_servicios.cliente'),
        ),
    ]
