# Generated by Django 5.2.6 on 2025-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0018_presupuesto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
