# Generated by Django 5.2.6 on 2025-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0020_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
