# Generated by Django 5.2.6 on 2025-11-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0021_ordentrabajo_pago'),
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaciontecnico',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tecnicos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleinspeccion',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_inspeccion', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleordentrabajo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden_trabajo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_presupuesto', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenordentrabajo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_orden_trabajo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_vehiculo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcas_vehiculos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_vehiculos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaordentrabajo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas_orden_trabajo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebaruta',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ruta', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareaordentrabajo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_orden_trabajo', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
    ]
