# Generated by Django 5.2.6 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0022_area_tenant_asignaciontecnico_tenant_and_more'),
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_placa',
            field=models.CharField(error_messages={'blank': 'El número de placa es obligatorio.', 'null': 'El número de placa es obligatorio.', 'unique': 'Ya existe un vehículo con este número de placa.'}, max_length=20, verbose_name='Número de Placa'),
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('nombre', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('nombre', 'marca', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('numero_placa', 'tenant')},
        ),
    ]
