# Generated by Django 5.2.6 on 2025-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_inventario', '0023_alter_vehiculo_unique_together_alter_marca_nombre_and_more'),
        ('personal_admin', '0012_alter_cargo_nombre_alter_empleado_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('codigo', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('nombre', 'tenant')},
        ),
    ]
