# Generated by Django 5.2.6 on 2025-11-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
        ('servicios_IA', '0002_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturaplaca',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_placa', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='personal_admin.tenant'),
            preserve_default=False,
        ),
    ]
