# Generated by Django 5.2.6 on 2025-10-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_servicios', '0001_initial'),
        ('operaciones_inventario', '0020_proveedor'),
        ('personal_admin', '0008_alter_bitacora_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('tipo_cita', models.CharField(choices=[('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('diagnostico', 'Diagnóstico'), ('entrega', 'Entrega')], default='reparacion', max_length=20, verbose_name='Tipo de Cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes_servicios.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='personal_admin.empleado', verbose_name='Empleado')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='operaciones_inventario.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora_inicio'],
                'indexes': [models.Index(fields=['fecha_hora_inicio'], name='clientes_se_fecha_h_5615b0_idx'), models.Index(fields=['estado'], name='clientes_se_estado_8f874f_idx'), models.Index(fields=['empleado'], name='clientes_se_emplead_1716b5_idx')],
            },
        ),
    ]
