# Generated by Django 5.2.6 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_servicios', '0003_cita_tenant_cliente_tenant'),
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('nit', 'tenant')},
        ),
    ]
