# Generated by Django 5.2.6 on 2025-10-21 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones_inventario', '0019_presupuesto_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia Bancaria'), ('stripe', 'Stripe'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Payment Intent ID de Stripe')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Charge ID de Stripe')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer ID de Stripe')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='operaciones_inventario.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['orden_trabajo', 'estado'], name='pagos_orden_t_5aafb7_idx'), models.Index(fields=['fecha_pago'], name='pagos_fecha_p_8536b9_idx'), models.Index(fields=['stripe_payment_intent_id'], name='pagos_stripe__409b43_idx')],
            },
        ),
    ]
