# Generated by Django 5.2.6 on 2025-11-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_facturacion', '0001_initial'),
        ('operaciones_inventario', '0020_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='operaciones_inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Factura de Proveedor',
                'verbose_name_plural': 'Facturas de Proveedor',
                'db_table': 'factura_proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='operaciones_inventario.item')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='finanzas_facturacion.facturaproveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Proveedor',
                'verbose_name_plural': 'Detalles de Factura de Proveedor',
                'db_table': 'detalle_factura_proveedor',
                'ordering': ['id'],
            },
        ),
    ]
