# Generated by Django 5.2.6 on 2025-11-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='currency',
            field=models.CharField(default='bob', help_text='Código de moneda (bob, usd, etc.)', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descripcion',
            field=models.TextField(blank=True, default='Pago de servicio de taller', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='ID del Payment Intent creado en Stripe', max_length=255, null=True, verbose_name='Payment Intent ID de Stripe'),
        ),
    ]
