# Generated by Django 5.2.6 on 2025-11-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_facturacion', '0002_facturaproveedor_detallefacturaproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto calculado del descuento', max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto calculado del IVA', max_digits=10),
        ),
    ]
