# Generated by Django 5.2.6 on 2025-11-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_facturacion', '0002_remove_pago_stripe_charge_id_and_more'),
        ('finanzas_facturacion', '0003_facturaproveedor_descuento_porcentaje_and_more'),
    ]

    operations = [
    ]
