# Generated by Django 5.2.6 on 2025-11-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_facturacion', '0004_merge_20251101_2334'),
        ('personal_admin', '0011_bitacora_tenant_cargo_tenant_empleado_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturaproveedor',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura_proveedor', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='personal_admin.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='personal_admin.tenant'),
            preserve_default=False,
        ),
    ]
